<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst(str_replace('_', ' ', $report_type)) }} - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #007bff;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #007bff;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary {
            background-color: #f8f9fa;
            padding: 15px;
            margin-bottom: 25px;
            border-radius: 5px;
        }
        .summary-item {
            display: inline-block;
            margin: 5px 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ ucfirst(str_replace('_', ' ', $report_type)) }}</h1>
        <p>{{ \Carbon\Carbon::parse($start_date)->format('M j, Y') }} - {{ \Carbon\Carbon::parse($end_date)->format('M j, Y') }}</p>
        <p>Generated on {{ $generated_at->format('M j, Y g:i A') }}</p>
    </div>

    @if(isset($summary))
    <div class="summary">
        <h3>Summary</h3>
        <div class="summary-item">
            <strong>Total Members:</strong> {{ number_format($summary['total_members']) }}
        </div>
        <div class="summary-item">
            <strong>New Members:</strong> {{ number_format($summary['new_members']) }}
        </div>
        <div class="summary-item">
            <strong>Active Members:</strong> {{ number_format($summary['active_members']) }}
        </div>
        <div class="summary-item">
            <strong>Members with Loans:</strong> {{ number_format($summary['members_with_loans']) }}
        </div>
    </div>
    @endif

    @if(isset($members) && $members->isNotEmpty())
    <table>
        <thead>
            <tr>
                <th>Member Number</th>
                <th>Name</th>
                <th>Email</th>
                <th>Status</th>
                <th>Joined</th>
                <th>Accounts</th>
                <th>Loans</th>
            </tr>
        </thead>
        <tbody>
            @foreach($members as $member)
            <tr>
                <td>{{ $member->member_number }}</td>
                <td>{{ $member->first_name }} {{ $member->last_name }}</td>
                <td>{{ $member->email }}</td>
                <td>{{ ucfirst($member->membership_status ?? 'active') }}</td>
                <td>{{ $member->created_at->format('M j, Y') }}</td>
                <td>{{ $member->accounts->count() }}</td>
                <td>{{ $member->loans->count() }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>This report was generated automatically by the SACCO Management System.</p>
        <p>Generated by: {{ auth()->user()->first_name }} {{ auth()->user()->last_name }}</p>
    </div>
</body>
</html> 