<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst(str_replace('_', ' ', $report_type)) }} - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #007bff;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #007bff;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h3 {
            background-color: #f8f9fa;
            padding: 10px;
            margin: 0 0 15px 0;
            border-left: 4px solid #007bff;
            font-size: 16px;
        }
        .row {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid #eee;
        }
        .total-row {
            font-weight: bold;
            background-color: #f8f9fa;
            padding: 12px;
            margin-top: 10px;
        }
        .positive {
            color: #28a745;
        }
        .negative {
            color: #dc3545;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ ucfirst(str_replace('_', ' ', $report_type)) }}</h1>
        <p>{{ \Carbon\Carbon::parse($start_date)->format('M j, Y') }} - {{ \Carbon\Carbon::parse($end_date)->format('M j, Y') }}</p>
        <p>Generated on {{ $generated_at->format('M j, Y g:i A') }}</p>
    </div>

    @if($report_type === 'income_statement' && isset($income))
    <div class="section">
        <h3>Revenue</h3>
        <div class="row">
            <span>Interest Income</span>
            <span>KSh {{ number_format($income['loan_interest'] ?? 0, 2) }}</span>
        </div>
        <div class="row">
            <span>Fee Income</span>
            <span>KSh {{ number_format($income['fees'] ?? 0, 2) }}</span>
        </div>
        <div class="total-row">
            <div class="row">
                <span>Total Revenue</span>
                <span class="positive">KSh {{ number_format($total_income, 2) }}</span>
            </div>
        </div>
    </div>

    <div class="section">
        <h3>Expenses</h3>
        <div class="row">
            <span>Operational Expenses</span>
            <span>KSh {{ number_format($total_expenses, 2) }}</span>
        </div>
        <div class="total-row">
            <div class="row">
                <span>Total Expenses</span>
                <span class="negative">KSh {{ number_format($total_expenses, 2) }}</span>
            </div>
        </div>
    </div>

    <div class="section">
        <h3>Net Income</h3>
        <div class="total-row">
            <div class="row">
                <span style="font-size: 16px;">Net Income</span>
                <span style="font-size: 16px;" class="{{ $net_income >= 0 ? 'positive' : 'negative' }}">
                    KSh {{ number_format($net_income, 2) }}
                </span>
            </div>
        </div>
    </div>
    @else
    <div class="section">
        <p style="text-align: center; color: #666; font-style: italic;">
            Report data will be displayed here when available.
        </p>
    </div>
    @endif

    <div class="footer">
        <p>This report was generated automatically by the SACCO Management System.</p>
        <p>Generated by: {{ auth()->user()->first_name }} {{ auth()->user()->last_name }}</p>
    </div>
</body>
</html> 